version: '3'

services:
   mysql-docker-container:
      container_name: mysql-docker-container
      image: mysql:5.7
      environment:
        - MYSQL_ROOT_PASSWORD=12345
        - MYSQL_DATABASE=MyAppDb
        - MYSQL_USER=myapp-user
        - MYSQL_PASSWORD=password
      ports:
        - 3306:3306
      networks:
        - employee-mysql
      restart: always
      volumes:
         - /data/mysql
      
   jade-poc-container:
      image: jade-poc-app
      build:
        context: ./
        dockerfile: Dockerfile
      restart: always
      networks:
        - employee-mysql
      depends_on:
        - mysql-docker-container
      ports:
        - 8080:8080
      volumes:
        - /data/spring-boot-app
    
networks:
  employee-mysql:
    driver: bridge
    
 